// <auto-generated />
namespace BakeCake.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changeModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeModels));
        
        string IMigrationMetadata.Id
        {
            get { return "201707022017112_changeModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
